![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np

my_array= np.arange(0,10,1)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(my_array[my_array%2!=0][::-1])


[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [13]:
print(my_array[7:9][::-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [17]:
print(my_array[0:3][::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [97]:
liste= np.arange(20)+1 
liste_nueva = liste.reshape((4,5))
liste_nueva


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [49]:
(np.arange(1,21))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
np.full((4,5), " ")

array([[' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ']], dtype='<U1')

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [98]:
pedazo = liste_nueva
pedazo[:2, :2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [119]:
liste_nueva



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [148]:
liste_nueva[0:5:2, 0:5:2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [188]:
liste_nueva

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [16, 17, 18, 19, 20]])

In [191]:
matriz=np.flip(liste_nueva[0:3:1, 0:5:1])
print(matriz)

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [195]:
matriz

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [197]:
matriz[[0, 2]] = matriz[[2, 0]]
matriz

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [201]:
matriz[2] = [15, 14, 13, 12, 11]
matriz


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [224]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

arr_index = np.where(x == 'Loro',"Loro","") #Manera 1
print(arr_index)



['Loro' '' '' 'Loro' '']


In [230]:
x1=x[0]
x1

'Loro'

In [231]:
x2=x[3]
x2

'Loro'

In [232]:
x3 = x1 + ", " + x2 #manera 2
x3

'Loro, Loro'

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [245]:
list1= np.arange(20)+1
list1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [247]:
nueva_lista = list1.reshape((5,2))*2

ValueError: cannot reshape array of size 20 into shape (5,2)

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [252]:
np.flip(liste_nueva)

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [259]:
array11 = [0] * 10
print (array11)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [262]:
np.size(array11)

10

In [263]:
import sys
sys.getsizeof(array11)

136

In [260]:
array11[3] = 1
array11

[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [280]:
vector = np.arange(10,50)
vector





array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [281]:
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [282]:
vector = [1,2,0,0,4,0]

In [285]:
nuevo_vector = np.where(vector != 1,1,"") 
print(nuevo_vector)


1


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [296]:
matrix = np.random.randint(100,size=(10,10))
matrix

array([[78, 88, 39, 75, 69, 51, 28, 68, 33, 57],
       [20, 18, 47, 46, 60, 99, 22, 15, 56, 80],
       [19, 25, 37, 29,  5, 60, 69, 78,  2, 28],
       [17, 46, 98, 50, 35, 55,  5, 87, 15,  2],
       [62, 77, 71, 31, 17, 95, 83, 69, 49, 73],
       [60, 68, 93, 18, 58, 37, 23, 46, 57, 15],
       [75, 84, 36, 71, 34, 72, 63, 83, 31, 41],
       [90, 81, 47, 11, 10, 68, 93, 32, 99, 92],
       [44, 47, 69, 59, 81, 27,  5, 42, 45, 19],
       [91, 33, 23, 88, 32, 17, 69, 20, 57, 76]])

In [299]:
np.max(matrix)

99

In [300]:
np.min(matrix)

2

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [303]:
matrix1 = np.random.randint(100,size=(30))
matrix1

array([74,  7, 72, 21, 70, 86,  4, 54, 20, 24, 73,  3, 21, 26, 99, 20, 62,
        5, 73, 91, 49, 79, 92, 16, 31,  8, 97, 74, 12, 71])

In [304]:
np.mean(matrix1)

47.8

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [315]:
matrix16 = np.random.randint(1,size=(2,6))
matrix16

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [316]:
matrix16[0,0] = 1
matrix16

array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [317]:
matrix16[1,0] = 1
matrix16

array([[1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0]])

In [318]:
matrix16[0,5] = 1
matrix16

array([[1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0]])

In [319]:
matrix16[1,5] = 1
matrix16

array([[1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [15]:
tablero = np.full((8,8), 1)
tablero

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [4]:
import numpy as np



In [19]:
np.arange(tablero)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [9]:
tablero = np.where[(0:, :7), 1,2]

SyntaxError: invalid syntax (4219452769.py, line 1)

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [326]:
np.tile(tablero,8)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [361]:
otro_tablero = np.full((5,5),[np.random.randint(100)])
otro_tablero #intento 1

array([[51, 51, 51, 51, 51],
       [51, 51, 51, 51, 51],
       [51, 51, 51, 51, 51],
       [51, 51, 51, 51, 51],
       [51, 51, 51, 51, 51]])

In [366]:
 tablero_w = np.random.randint(1, 30, size=(5, 5))
tablero_w #intento 2

array([[10, 15,  2, 19, 10],
       [13, 25,  9, 16, 22],
       [16,  6, 21, 19, 19],
       [ 5, 26, 17, 23,  6],
       [15, 29, 29, 27, 27]])

In [372]:
promedio = np.mean(tablero_w)
promedio

17.04

In [373]:
desviacion = np.std(tablero_w)
desviacion

7.799897435223107

In [375]:
normalizar = ((tablero_w - promedio))/ desviacion
normalizar

array([[-0.90257597, -0.2615419 , -1.92823048,  0.25128536, -0.90257597],
       [-0.51795553,  1.02052624, -1.03078278, -0.13333509,  0.6359058 ],
       [-0.13333509, -1.41540323,  0.50769898,  0.25128536,  0.25128536],
       [-1.54361004,  1.14873305, -0.00512827,  0.76411261, -1.41540323],
       [-0.2615419 ,  1.5333535 ,  1.5333535 ,  1.27693987,  1.27693987]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [376]:
numeros_x= np.arange(0,11,1)
numeros_x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [380]:
numeros_x[3:9]
nuevo_numeros

array([3, 4, 5, 6, 7, 8])

In [384]:
numeros_x[3:9] = -1

In [385]:
numeros_x

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [46]:
tablero3 = np.full((10,10), "")
tablero3

array([['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [47]:
tablero3[(0,1),(1,1)] = "O"
tablero3

array([['', 'O', '', '', '', '', '', '', '', ''],
       ['', 'O', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [48]:
tablero3[(1,3), (1,4)] = "O"
#tablero3[(1,3), (1,4), (1,5), (1,6)] = "O"
tablero3

array([['', 'O', '', '', '', '', '', '', '', ''],
       ['', 'O', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', 'O', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [49]:
tablero3[(1,5), (1,6)] = "O"
#tablero3[(1,3), (1,4), (1,5), (1,6)] = "O"
tablero3

array([['', 'O', '', '', '', '', '', '', '', ''],
       ['', 'O', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', 'O', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', 'O', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [50]:
tablero3[(3,4)] = "X"
tablero3

array([['', 'O', '', '', '', '', '', '', '', ''],
       ['', 'O', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', 'X', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', 'O', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [51]:
tablero3[(7,5)] = "-"
tablero4 = tablero3
tablero4

array([['', 'O', '', '', '', '', '', '', '', ''],
       ['', 'O', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', 'X', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', 'O', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '-', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

In [55]:
n_barcos = 3
size = 4

while n_barcos >= 1:
    
    if np.random.randint(0,2,1):
        coord1 = np.random.randint(0,10)
        coord2 = np.random.randint(0,10-size+1)
        
        if "O" in tablero4[coord1, coord2:coord2+size]:
            pass
        else: 
            tablero4[coord1, coord2:coord2+size] = "O"
            n_barcos -= 1
    else:
        coord2 = np.random.randint(0,10)
        coord1 = np.random.randint(0,10-size+1)
        
        if "O" in tablero4[coord1:coord1+size, coord2]:
            pass
        else: 
            tablero4[coord1:coord1+size, coord2] = "O"
            n_barcos -= 1


In [43]:
tablero3

array([['', 'O', '', 'O', '', '', '', '', '', ''],
       ['', 'O', '', 'O', '', '', '', '', '', ''],
       ['', '', '', 'O', '', '', '', '', '', ''],
       ['', '', '', 'O', 'X', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', 'O', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '-', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**