![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
print(np.__version__) #saber version de cualquier libreria


1.26.4


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [7]:
my_array = np.arange(0,10,1)
print(my_array)



[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [51]:
otro_array = np.full((3,3), True)
otro_array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
np.ones((3,3)) ==1 #otra forma v1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
np.ones((3,3)).astype(bool) #otra forma v2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [14]:
my_array = np.arange(0,10,1)

np.where(my_array%2!=0) #es un filtro / o devuelve el filtro, o sustituye var1 por var2


(array([1, 3, 5, 7, 9], dtype=int64),)

In [12]:
my_array%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [13]:
my_array[my_array%2!=0] #Solo con impares

array([1, 3, 5, 7, 9])

In [16]:
np.where(my_array%2!=0, -1, np.where(my_array>3, 10, 20)) #regla de que si cumple el filtro then a, 
#si no cumple primer filtro pasa a la siguiente, iferror / if>dentro otro if
# es necesario guardar la variable: var_nueva = np.where

array([20, -1, 20, -1, 10, -1, 10, -1, 10, -1])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [23]:
new_my_array = np.where(my_array%2!=0, -1, my_array) #guardar la variable SIEMPRE
new_my_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
my_array[my_array%2!=0] = -1
my_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [25]:
a = np.ones((6,3)) #se puede modificar siempre que hayan 18 cosas = 6x3
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
a.reshape(3,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
a.reshape(2,-1) #el -1 le da la opcion a np a recalcularlo

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
a.reshape(-1) #esta dimension calculala tu

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [30]:
a.reshape(-1, -1) #error, solo puede adivinar una variable

ValueError: can only specify one unknown dimension

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [33]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)  #esto no es
c = a + b
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
a,b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [36]:
np.concatenate([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [38]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b) #coinciden 2 y 4 (vlookup)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [39]:
my_array[0]
my_array[-1]

-1

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [40]:
range[1,50,3]

TypeError: 'type' object is not subscriptable

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [ ]:
imagen = [notebook]

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [ ]:
reshape

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [44]:
# 4 cosas de 5 cosas con 3 cosas

np.random.rand(4,5,3)

array([[[0.54928487, 0.90523558, 0.59449121],
        [0.40672302, 0.93745758, 0.03960309],
        [0.07940314, 0.03064854, 0.16943269],
        [0.35171336, 0.12128517, 0.47183829],
        [0.65430652, 0.33012577, 0.02235356]],

       [[0.00584148, 0.74799808, 0.7525967 ],
        [0.65965016, 0.87719506, 0.63341323],
        [0.20524402, 0.22943952, 0.79284397],
        [0.34488462, 0.74148369, 0.82667899],
        [0.91478695, 0.34406405, 0.99745175]],

       [[0.24248219, 0.41732833, 0.17017239],
        [0.52926995, 0.63628627, 0.35394688],
        [0.46719218, 0.70959295, 0.22867316],
        [0.2110728 , 0.1659204 , 0.87867954],
        [0.34230514, 0.27237072, 0.15653021]],

       [[0.38975398, 0.94136011, 0.20079252],
        [0.77263114, 0.66552347, 0.36365602],
        [0.80567417, 0.74163091, 0.62315565],
        [0.05725045, 0.57932316, 0.30782031],
        [0.96295161, 0.3767242 , 0.21433231]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [ ]:
# 1. elemento 5*2*6
# 2. dimensiones son la longitud
# 3. elementos shape[0], shape[1], shape[2]
#1:24 grabacion

In [45]:
x=np.random.randint(10,20, size=(5,2,6))

In [46]:
x.size

60

In [50]:
x.ndim

3

In [51]:
for numero in range(x.ndim):
    print(f"la dimension {numero} tiene {x.shape[numero]} elementos")

la dimension 0 tiene 5 elementos
la dimension 1 tiene 2 elementos
la dimension 2 tiene 6 elementos
